export {default as hero } from './Hero.svelte'
export {default as projects_container } from './ProjectsContainer.svelte'
export {default as slidedeck } from './SlideDeck.svelte'
export {default as tools } from './Tools.svelte'
export {default as contact_info } from './ContactInfo.svelte'
